In [34]:
import numpy as np

fheader = "headernames.data"
fdata = [
         "cleveland.data",
         "hungarian.data",
         "long-beach-va.data",
         "switzerland.data",
        ]

with open(fheader, 'r', encoding='ascii') as f:
    headers = [word for line in f for word in line.split()]

len(headers)

76

In [35]:
import pandas as pd

data_processed = []

for i in range(len(fdata)):
    with open(fdata[i], 'r', encoding='ascii') as f:
        values = [word for line in f for word in line.split()]
        data_processed.append(np.reshape(np.array(values), (-1, 76)))
    n = np.shape(data_processed[i])[0]
    data_processed[i] = np.column_stack((np.repeat(i, n), data_processed[i]))

for d in data_processed:
    print(np.shape(d))
    
data_processed = np.vstack(data_processed)

frame = pd.DataFrame.from_records(data_processed, columns=np.array(['dataset'] + headers))

age_series = frame['age']
sex_series = frame['sex']
# Added in two features, one corresponding to sex and one to age.
# Both are aggregate features corresponding to percentage frequency
# of coronary heart disease
sex_feature = [(7.2 if x == "1" else 4.3) for x in sex_series]
age_feature = []
for age in age_series:
    num = int(age)
    if (num < 18):
        age_feature.append(0)
    elif (num < 45):
        age_feature.append(0.8)
    elif (num < 65):
        age_feature.append(6.1)
    elif (num < 75):
        age_feature.append(16.4)
    else:
        age_feature.append(23.3)
frame['age_feature'] = age_feature
frame['sex_feature'] = sex_feature
frame

(282, 77)
(294, 77)
(200, 77)
(123, 77)

,dataset,id,ccf,age,sex,painloc,painexer,relrest,pncaden,cp,...,lvx1,lvx2,lvx3,lvx4,lvf,cathef,junk,name,age_feature,sex_feature
0,0,1,0,63,1,-9,-9,-9,-9,1,...,1,1,1,1,1,-9,-9,name,6.1,7.2
1,0,2,0,67,1,-9,-9,-9,-9,4,...,1,1,1,1,1,-9,-9,name,16.4,7.2
2,0,3,0,67,1,-9,-9,-9,-9,4,...,1,1,1,7,3,-9,-9,name,16.4,7.2
3,0,4,0,37,1,-9,-9,-9,-9,3,...,1,1,1,1,1,-9,-9,name,0.8,7.2
4,0,6,0,41,0,-9,-9,-9,-9,2,...,1,1,1,1,1,-9,-9,name,0.8,4.3
5,0,7,0,56,1,-9,-9,-9,-9,2,...,1,1,1,1,1,-9,-9,name,6.1,7.2
6,0,8,0,62,0,-9,-9,-9,-9,4,...,1,1,1,7,1,-9,-9,name,6.1,4.3
7,0,9,0,57,0,-9,-9,-9,-9,4,...,1,1,1,1,1,-9,-9,name,6.1,4.3
8,0,10,0,63,1,-9,-9,-9,-9,4,...,1,1,6,7,2,-9,-9,name,6.1,7.2
9,0,11,0,53,1,-9,-9,-9,-9,4,...,1,1,1,1,1,-9,-9,name,6.1,7.2
10,0,12,0,57,1,-9,-9,-9,-9,4,...,1,1,1,1,1,-9,-9,name,6.1,7.2
11,0,13,0,56,0,-9,-9,-9,-9,2,...,1,1,1,1,1,-9,-9,name,6.1,4.3
12,0,14,0,56,1,-9,-9,-9,-9,3,...,1,1,1,3,1,-9,-9,name,6.1,7.2
13,0,15,0,44,1,-9,-9,-9,-9,2,...,1,1,1,1,1,-9,-9,name,0.8,7.2
14,0,16,0,52,1,-9,-9,-9,-9,3,...,1,1,1,1,1,-9,-9,name,6.1,7.2
15,0,17,0,57,1,-9,-9,-9,-9,3,...,1,1,1,1,1,-9,-9,name,6.1,7.2
16,0,18,0,48,1,-9,-9,-9,-9,2,...,1,1,1,1,1,-9,-9,name,6.1,7.2
17,0,19,0,54,1,-9,-9,-9,-9,4,...,1,1,1,1,1,-9,-9,name,6.1,7.2
18,0,20,0,48,0,-9,-9,-9,-9,3,...,1,1,1,1,1,-9,-9,name,6.1,4.3
19,0,21,0,49,1,-9,-9,-9,-9,2,...,1,1,1,1,1,-9,-9,name,6.1,7.2
20,0,22,0,64,1,-9,-9,-9,-9,1,...,1,1,1,1,1,-9,-9,name,6.1,7.2
21,0,23,0,58,0,-9,-9,-9,-9,1,...,1,1,1,1,1,-9,-9,name,6.1,4.3
22,0,24,0,58,1,-9,-9,-9,-9,2,...,1,1,1,1,1,-9,-9,name,6.1,7.2
23,0,25,0,58,1,-9,-9,-9,-9,3,...,1,1,1,8,3,-9,-9,name,6.1,7.2
24,0,26,0,60,1,-9,-9,-9,-9,4,...,1,1,1,1,1,-9,-9,name,6.1,7.2
25,0,27,0,50,0,-9,-9,-9,-9,3,...,1,1,1,1,1,-9,-9,name,6.1,4.3
26,0,28,0,58,0,-9,-9,-9,-9,3,...,1,1,1,1,1,-9,-9,name,6.1,4.3
27,0,29,0,66,0,-9,-9,-9,-9,1,...,1,1,1,1,1,-9,-9,name,16.4,4.3
28,0,30,0,43,1,-9,-9,-9,-9,4,...,1,1,1,1,1,-9,-9,name,0.8,7.2
29,0,31,0,40,1,-9,-9,-9,-9,4,...,1,1,1,1,1,-9,-9,name,0.8,7.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
869,3,4044,0,42,1,1,1,1,-9,4,...,-9,-9,-9,-9,-9,-9.,-9.,name,0.8,7.2
870,3,4045,0,53,1,1,1,1,-9,4,...,1,1,1,1,2,59,-9.,name,6.1,7.2
871,3,4046,0,55,1,1,1,1,-9,4,...,1,1,1,1,1,60,-9.,name,6.1,7.2
872,3,4047,0,61,1,1,1,1,-9,4,...,1,1,1,1,1,76,-9.,name,6.1,7.2
873,3,4048,0,51,1,1,1,1,-9,4,...,1,1,1,1,2,83,-9.,name,6.1,7.2
874,3,4049,0,70,1,1,1,1,-9,4,...,1,1,1,1,1,73,-9.,name,16.4,7.2
875,3,4050,0,61,1,1,1,1,-9,4,...,1,1,1,1,2,62,-9.,name,6.1,7.2
876,3,4051,0,38,1,1,1,1,-9,4,...,1,1,1,1,1,74,-9.,name,0.8,7.2
877,3,4052,0,57,1,1,1,1,-9,4,...,1,1,1,1,1,69,-9.,name,6.1,7.2
878,3,4053,0,38,1,1,1,1,-9,4,...,7,1,1,1,2,62,-9.,name,0.8,7.2
879,3,4054,0,62,0,0,0,0,-9,1,...,1,1,1,1,1,-9.,-9.,name,6.1,4.3
880,3,4055,0,58,1,1,1,1,-9,4,...,1,1,1,1,1,80,-9.,name,6.1,7.2
881,3,4056,0,52,1,1,1,1,-9,4,...,1,1,1,1,1,76,-9.,name,6.1,7.2
882,3,4057,0,61,1,1,0,0,-9,3,...,1,1,1,1,1,68,-9.,name,6.1,7.2
883,3,4058,0,50,0,1,1,1,-9,4,...,1,1,1,1,1,-9.,-9.,name,6.1,4.3
884,3,4059,0,51,1,1,1,1,-9,4,...,1,1,1,1,1,66,-9.,name,6.1,7.2
885,3,4060,0,65,1,1,1,1,-9,4,...,3,1,1,1,3,63,-9.,name,16.4,7.2
886,3,4061,0,52,1,1,1,1,-9,4,...,1,1,1,1,1,67,-9.,name,6.1,7.2
887,3,4062,0,47,1,1,1,1,-9,3,...,1,1,1,1,1,60,-9.,name,6.1,7.2
888,3,4063,0,35,1,1,1,1,-9,4,...,1,1,5,3,3,68,-9.,name,0.8,7.2
889,3,4064,0,57,1,1,1,1,-9,4,...,1,1,1,1,1,67,-9.,name,6.1,7.2
890,3,4065,0,62,1,1,1,1,-9,4,...,1,1,1,1,1,-9.,-9.,name,6.1,7.2
891,3,4067,0,59,1,1,1,1,-9,4,...,1,1,5,3,3,58,-9.,name,6.1,7.2
892,3,4068,0,53,1,1,1,1,-9,3,...,1,1,1,1,1,71,-9.,name,6.1,7.2
893,3,4069,0,62,1,1,1,1,-9,4,...,3,5,7,8,4,49,-9.,name,6.1,7.2
894,3,4070,0,54,1,1,1,1,-9,4,...,1,1,1,1,1,71,-9.,name,6.1,7.2
895,3,4071,0,56,1,1,1,1,-9,4,...,5,1,1,1,2,68,-9.,name,6.1,7.2
896,3,4072,0,56,1,0,1,1,-9,3,...,1,1,5,3,2,61,-9.,name,6.1,7.2
897,3,4073,0,54,1,1,1,1,-9,4,...,1,1,1,1,1,-9.,-9.,name,6.1,7.2
898,3,4074,0,66,0,1,1,1,-9,4,...,1,1,1,1,1,70,-9.,name,16.4,4.3

In [36]:
# delete names
del frame['name']

In [37]:
# convert to numbers
frame = frame.applymap(float)
# responses
# Y = frame['num'].map(lambda x: 1 if x != 0 else 0)

# delete "garbage columns" that only have one value for the healthy
# as they probably just describe the response

#for k in frame.keys():
#    if frame[k][Y == 0].nunique() == 1:
#        print('frame ' + k)
#        del frame[k]

In [38]:
# break down categorical variables
flatten = lambda x: 1 if x else 0
factors = ['cp', 'restecg', 'proto', 'slope', 'restwm', 'thal', 'dataset']

for factor in factors:
    if factor in frame:
        for value in frame[factor].unique():
            frame[factor + str(int(value))] = (frame[factor] == value).map(flatten)
        del frame[factor]

In [39]:
problematic_cols = [k for k in frame.keys() if any(frame[k] == -9)]
print('Formerly problematic:', problematic_cols)

# fill in invalid data with the mean
for k in frame.keys():
    if frame[k].isin([-9])[0]:
        frame[k + '_invalid'] = frame[k].map(lambda x: 1 if x == -9 else 0)
    
problematic_cols = [k for k in frame.keys() if any(frame[k] == -9)]
print('Now problematic:', problematic_cols)

Formerly problematic: ['painloc', 'painexer', 'relrest', 'pncaden', 'trestbps', 'htn', 'chol', 'smoke', 'cigs', 'years', 'fbs', 'dm', 'famhist', 'ekgmo', 'ekgday', 'ekgyr', 'dig', 'prop', 'nitr', 'pro', 'diuretic', 'thaldur', 'thaltime', 'met', 'thalach', 'thalrest', 'tpeakbps', 'tpeakbpd', 'dummy', 'trestbpd', 'exang', 'xhypo', 'oldpeak', 'rldv5', 'rldv5e', 'ca', 'restckm', 'exerckm', 'restef', 'exeref', 'exerwm', 'thalsev', 'thalpul', 'earlobe', 'cmo', 'cday', 'cyr', 'lmt', 'ladprox', 'laddist', 'diag', 'cxmain', 'ramus', 'om1', 'om2', 'rcaprox', 'rcadist', 'lvx1', 'lvx2', 'lvx3', 'lvx4', 'lvf', 'cathef', 'junk']
Now problematic: ['painloc', 'painexer', 'relrest', 'pncaden', 'trestbps', 'htn', 'chol', 'smoke', 'cigs', 'years', 'fbs', 'dm', 'famhist', 'ekgmo', 'ekgday', 'ekgyr', 'dig', 'prop', 'nitr', 'pro', 'diuretic', 'thaldur', 'thaltime', 'met', 'thalach', 'thalrest', 'tpeakbps', 'tpeakbpd', 'dummy', 'trestbpd', 'exang', 'xhypo', 'oldpeak', 'rldv5', 'rldv5e', 'ca', 'restckm', 'exerckm', 'restef', 'exeref', 'exerwm', 'thalsev', 'thalpul', 'earlobe', 'cmo', 'cday', 'cyr', 'lmt', 'ladprox', 'laddist', 'diag', 'cxmain', 'ramus', 'om1', 'om2', 'rcaprox', 'rcadist', 'lvx1', 'lvx2', 'lvx3', 'lvx4', 'lvf', 'cathef', 'junk']

In [40]:
frame.to_csv('./229_processed_full.data')

In [41]:
Y.to_csv('./229_processed_Y_full.data')

NameError: name 'Y' is not defined

In [42]:
Y

NameError: name 'Y' is not defined

In [43]:
N = len(Y)
test_i = np.random.permutation(np.arange(N))[0:(N//6)]
train_i = np.random.permutation(np.arange(N))[(N//6):]

test_frame = frame[frame.index.isin(test_i)]
train_frame = frame[frame.index.isin(train_i)]

Y_test_frame = Y[frame.index.isin(test_i)]
Y_train_frame = Y[frame.index.isin(train_i)]

NameError: name 'Y' is not defined

In [44]:
test_frame.to_csv('./new_test_X.data')
train_frame.to_csv('./new_train_X.data')

Y_test_frame.to_csv('./new_test_Y.data')
Y_train_frame.to_csv('./new_train_Y.data')

NameError: name 'test_frame' is not defined

In [45]:
Y_train_frame

NameError: name 'Y_train_frame' is not defined